FROM htcondor/mini:9.10-el7

# We didn't create a CA certificate, so we have to munge the system bundle
# by hand.

COPY secrets/tls.crt   /certs/
COPY secrets/tls.key   /certs/
COPY util/add_cert.py  /certs/

RUN python3 /certs/add_cert.py /certs/tls.crt /etc/pki/tls/certs/ca-bundle.crt
