# Run SciTokens and other assorted commands implemented in Python.
#
# This image eliminates the need to set up a virtual environment or similar.

FROM python:3-slim

RUN python3 -m pip install --no-cache-dir scitokens
