FROM htcondor/mini:10.x-el8

# Install the TLS certificate.

COPY secrets/tls.crt secrets/tls.key /certs/
COPY util/add_cert.py /build/
RUN python3 /build/add_cert.py /certs/tls.crt /etc/pki/tls/certs/ca-bundle.crt
