---
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
# Modified by Brian Aydemir <baydemir@morgridge.org>.

version: "3.0"

#---------------------------------------------------------------------------

services:

  hub-db:
    image: postgres:14.2
    container_name: jupyterhub-db
    restart: always

    env_file:
    - secrets/postgres.env

    environment:
      PGDATA: ${DB_VOLUME_PATH}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
    - db:${DB_VOLUME_PATH}

  hub:
    depends_on:
    - htcondor
    - hub-db
    - token-issuer

    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}

    image: ${JUPYTERHUB_IMAGE}
    container_name: jupyterhub
    restart: always

    command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

    env_file:
    - secrets/oauth.env
    - secrets/postgres.env

    environment:
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}

      HUB_VOLUME_PATH: ${HUB_VOLUME_PATH}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: hub-db

      SINGLEUSER_IMAGE: ${SINGLEUSER_IMAGE}
      SINGLEUSER_CMD: ${SINGLEUSER_CMD}
      SINGLEUSER_VOLUME_PATH: ${SINGLEUSER_VOLUME_PATH}

      SCITOKENS_SERVICE_PORT: ${SCITOKENS_SERVICE_PORT}

    links:
    - hub-db

    ports:
    - 443:443

    secrets:
    - source: scitokens-service-config
      target: /etc/scitokens/jupyterhub_service.yaml

    volumes:
    - hub:${HUB_VOLUME_PATH}
    - /var/run/docker.sock:/var/run/docker.sock:rw

  token-issuer:
    image: hub.opensciencegrid.org/sciauth/lightweight-issuer:v1.0.2
    container_name: token-issuer.localdomain
    restart: always

    env_file:
    - secrets/oauth.env

    environment:
      HOSTNAME: localhost:8443

    ports:
    - 8443:8443

    secrets:
    - source: token-issuer-client
      target: ${TOKEN_ISSUER_VOLUME_PATH}/clients/dataPath/88df33a9eaba1514233748b188da33d584f38e24
    - source: token-issuer-client-approval
      target: ${TOKEN_ISSUER_VOLUME_PATH}/clientApprovals/dataPath/88df33a9eaba1514233748b188da33d584f38e24
    - source: token-issuer-keys
      target: /opt/scitokens-server/etc/keys.jwk
    - source: tls-crt
      target: /opt/tomcat/conf/hostcert.pem
    - source: tls-key
      target: /opt/tomcat/conf/hostkey.pem
    - source: token-issuer-user-config
      target: /opt/scitokens-server/var/qdl/user-config.txt

    volumes:
    - token-issuer:${TOKEN_ISSUER_VOLUME_PATH}

  htcondor:
    build:
      context: .
      dockerfile: Dockerfile.htcondor

    image: ${HTCONDOR_IMAGE}
    container_name: htcondor.localdomain
    restart: always

    ports:
    - 9618:9618

    secrets:
    - source: htcondor-end-to-end-env
      target: /etc/condor/config.d/90-end-to-end-env
    - source: htcondor-minicondor
      target: /etc/condor/config.d/00-minicondor
    - source: htcondor-mapfile
      target: /etc/condor/condor_mapfile

#---------------------------------------------------------------------------

## These "secrets" are used to inject files into the containers.

secrets:

  htcondor-minicondor:
    file: config/htcondor/00-minicondor

  htcondor-end-to-end-env:
    file: config/htcondor/90-end-to-end-env

  htcondor-mapfile:
    file: config/htcondor/condor_mapfile

  scitokens-service-config:
    file: secrets/jupyterhub_svc_config.yaml

  token-issuer-keys:
    file: secrets/token-issuer.jwks

  token-issuer-user-config:
    file: secrets/user-config.json

  token-issuer-client:
    file: config/token-issuer/clients/dataPath/88df33a9eaba1514233748b188da33d584f38e24

  token-issuer-client-approval:
    file: config/token-issuer/clientApprovals/dataPath/88df33a9eaba1514233748b188da33d584f38e24

  ## Shared TLS certificate and key.

  tls-crt:
    file: secrets/tls.crt
  tls-key:
    file: secrets/tls.key

## Create the networks and volumes below via `make build`.

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    external: true

volumes:
  hub:
    name: ${HUB_VOLUME_NAME}
    external: true
  db:
    name: ${DB_VOLUME_NAME}
    external: true
  token-issuer:
    name: ${TOKEN_ISSUER_VOLUME_NAME}
    external: true
