FROM htcondor/mini:10.2.0-el8

# Install configuration.

COPY config/htcondor/condor_mapfile /etc/condor/
COPY config/htcondor/90-end-to-end-env /etc/condor/config.d/

# Install the TLS certificate.

COPY secrets/tls.crt secrets/tls.key /certs/
COPY util/add_cert.py /build/
RUN python3 /build/add_cert.py /certs/tls.crt /etc/pki/tls/certs/ca-bundle.crt
