---
version: "3.0"

services:

  rest-demo:
    image: vuanh2103/cashman-flask:latest
    container_name: rest-demo
    restart: always

    environment:
      FLASK_APP: wsgi.py
      AUTH0_DOMAIN: dev-7jgsf20u.us.auth0.com
      API_IDENTIFIER: https://cashman/api

    secrets:
    - source: tls-crt
      target: /certs/tls.crt
    - source: tls-key
      target: /certs/tls.key

    ports:
    - 3001:8443
