oauth2:

- name: Lightweight Token Issuer
  id: lightweight-issuer

  auth_url: https://localhost:8443/scitokens-server/authorize
  token_url: https://token-issuer:8443/scitokens-server/token
  scope: openid

  device_auth_url: https://token-issuer:8443/scitokens-server/device_authorization

  client_id: oa4mp:/client_id/32163b076dd5194a29cc32849011c92f
  client_secret: ""
